name: gomoney_finance_app
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.0.0-nullsafety.11
  shared_preferences: ^2.0.4
  modal_bottom_sheet: ^2.0.0
  firebase_messaging: ^10.0.0
  permission_handler: ^7.1.0
  flutter_tesseract_ocr: ^0.3.6
  image_gallery_saver: ^1.6.9
  image_picker: ^0.7.5
  photo_view: ^0.11.1
  image_cropper: ^1.4.0
  flutter_isolate: ^2.0.0
  o_color_picker: ^1.0.1
  google_sign_in: ^5.0.3
  path_provider: ^2.0.1
  firebase_core: ^1.1.1
  firebase_auth: ^1.2.0
  currency_picker: ^2.0.4
  package_info: ^2.0.0
  url_launcher: ^6.0.2
  hive_flutter: ^1.0.0
  opencv_4: ^1.0.0
  flutter_svg: ^0.22.0  
  line_icons: ^2.0.1
  googleapis: ^2.0.0
  bot_toast: ^4.0.1
  fl_chart: ^0.36.1
  sqflite: ^2.0.0+3
  encrypt: ^5.0.0
  get_it: ^7.1.3
  http: ^0.13.3
  uuid: ^3.0.4
  hive: ^2.0.4
  path: ^1.8.0
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.3
  build_verify: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - fonts/MyFlutterApp.ttf
  - assets/
  - assets/tessdata/
  fonts: 
  - family: Prompt
    fonts:
        - asset: fonts/Prompt-Regular.ttf
        - asset: fonts/Prompt-Bold.ttf
          weight: 800
