name: gomoney_finance_app
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.0.0-nullsafety.11
  shared_preferences: ^2.0.5
  modal_bottom_sheet: ^2.0.0
  firebase_messaging: ^9.1.1
  cupertino_icons: ^1.0.2
  o_color_picker: ^1.0.1
  google_sign_in: ^5.0.1
  path_provider: ^2.0.1
  firebase_core: ^1.0.3
  firebase_auth: ^1.0.2
  package_info: ^2.0.0
  url_launcher: ^6.0.3
  hive_flutter: ^1.0.0
  line_icons: ^2.0.1
  bot_toast: ^4.0.1
  fl_chart: ^0.35.0
  sqflite: ^2.0.0+3
  date_util: ^0.1.4
  get_it: ^6.0.0
  http: ^0.13.1
  uuid: ^3.0.4
  hive: ^2.0.2
  path: ^1.8.0
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1
  build_runner: ^1.12.2

flutter:
  uses-material-design: true
  assets:
  - fonts/MyFlutterApp.ttf
  fonts: 
  - family: Prompt
    fonts:
        - asset: fonts/Prompt-Regular.ttf
        - asset: fonts/Prompt-Bold.ttf
          weight: 800
